#!/bin/sh

set -e

. scripts/config

exec 3<> "$PORT"
sleep 3

data='ola_r ola_g ola_b ola_w off'

for datum in $data; do
    printf '%s\n' "$datum"
    cat "data/$datum.bin" >&3
    sleep 0.5
done

exec 3>&-
